### ISSUE TITLE
`uvicorn==0.31.1` 无法安装

### ISSUE THREAD

**Issue by z0z0r4** [mcmod-info-mirror/mcim#107]
```
18.78 Building wheels for collected packages: httptools, uvloop
18.78   Building wheel for httptools (pyproject.toml): started
19.05   Building wheel for httptools (pyproject.toml): finished with status 'error'
19.07   error: subprocess-exited-with-error
19.07   
19.07   × Building wheel for httptools (pyproject.toml) did not run successfully.
19.07   │ exit code: 1
19.07   ╰─> [26 lines of output]
19.07       /tmp/pip-build-env-_z9z4q13/overlay/lib/python3.13/site-packages/setuptools/_distutils/dist.py:261: UserWarning: Unknown distribution option: 'test_suite'
19.07         warnings.warn(msg)
19.07       running bdist_wheel
19.07       running build
19.07       running build_py
19.07       creating build/lib.linux-x86_64-cpython-313/httptools
19.07       copying httptools/__init__.py -> build/lib.linux-x86_64-cpython-313/httptools
19.07       copying httptools/_version.py -> build/lib.linux-x86_64-cpython-313/httptools
19.07       creating build/lib.linux-x86_64-cpython-313/httptools/parser
19.07       copying httptools/parser/__init__.py -> build/lib.linux-x86_64-cpython-313/httptools/parser
19.07       copying httptools/parser/errors.py -> build/lib.linux-x86_64-cpython-313/httptools/parser
19.07       running egg_info
19.07       writing httptools.egg-info/PKG-INFO
19.07       writing dependency_links to httptools.egg-info/dependency_links.txt
19.07       writing requirements to httptools.egg-info/requires.txt
19.07       writing top-level names to httptools.egg-info/top_level.txt
19.07       reading manifest file 'httptools.egg-info/SOURCES.txt'
19.07       reading manifest template 'MANIFEST.in'
19.07       adding license file 'LICENSE'
19.07       writing manifest file 'httptools.egg-info/SOURCES.txt'
19.07       running build_ext
19.07       building 'httptools.parser.parser' extension
19.07       creating build/temp.linux-x86_64-cpython-313/httptools/parser
19.07       creating build/temp.linux-x86_64-cpython-313/vendor/llhttp/src
19.07       gcc -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O3 -Wall -fPIC -I/tmp/pip-install-fkwrynj9/httptools_c8984b493ee6409fb28b01e88c6cad9b/vendor/llhttp/include -I/tmp/pip-install-fkwrynj9/httptools_c8984b493ee6409fb28b01e88c6cad9b/vendor/llhttp/src -I/usr/local/include/python3.13 -c httptools/parser/parser.c -o build/temp.linux-x86_64-cpython-313/httptools/parser/parser.o -O2
19.07       error: command 'gcc' failed: No such file or directory
19.07       [end of output]
19.07   
19.07   note: This error originates from a subprocess, and is likely not a problem with pip.
19.07   ERROR: Failed building wheel for httptools
19.07   Building wheel for uvloop (pyproject.toml): started
20.73   Building wheel for uvloop (pyproject.toml): finished with status 'error'
20.75   error: subprocess-exited-with-error
20.75   
20.75   × Building wheel for uvloop (pyproject.toml) did not run successfully.
20.75   │ exit code: 1
20.75   ╰─> [260 lines of output]
20.75       running bdist_wheel
20.75       running build
20.75       running build_py
20.75       creating build/lib.linux-x86_64-cpython-313/uvloop
20.75       copying uvloop/_noop.py -> build/lib.linux-x86_64-cpython-313/uvloop
20.75       copying uvloop/__init__.py -> build/lib.linux-x86_64-cpython-313/uvloop
20.75       copying uvloop/_testbase.py -> build/lib.linux-x86_64-cpython-313/uvloop
20.75       copying uvloop/_version.py -> build/lib.linux-x86_64-cpython-313/uvloop
20.75       running egg_info
20.75       writing uvloop.egg-info/PKG-INFO
20.75       writing dependency_links to uvloop.egg-info/dependency_links.txt
20.75       writing requirements to uvloop.egg-info/requires.txt
20.75       writing top-level names to uvloop.egg-info/top_level.txt
20.75       reading manifest file 'uvloop.egg-info/SOURCES.txt'
20.75       reading manifest template 'MANIFEST.in'
20.75       warning: no previously-included files matching '*' found under directory 'vendor/libuv/.git'
20.75       warning: no previously-included files matching '*' found under directory 'vendor/libuv/docs'
20.75       warning: no previously-included files matching '*' found under directory 'vendor/libuv/img'
20.75       adding license file 'LICENSE-APACHE'
20.75       adding license file 'LICENSE-MIT'
20.75       writing manifest file 'uvloop.egg-info/SOURCES.txt'
20.75       /tmp/pip-build-env-cugjg79y/overlay/lib/python3.13/site-packages/setuptools/command/build_py.py:218: _Warning: Package 'uvloop.handles' is absent from the `packages` configuration.
20.75       !!
20.75       
20.75               ********************************************************************************
20.75               ############################
20.75               # Package would be ignored #
20.75               ############################
20.75               Python recognizes 'uvloop.handles' as an importable package[^1],
20.75               but it is absent from setuptools' `packages` configuration.
20.75       
20.75               This leads to an ambiguous overall configuration. If you want to distribute this
20.75               package, please make sure that 'uvloop.handles' is explicitly added
20.75               to the `packages` configuration field.
20.75       
20.75               Alternatively, you can also rely on setuptools' discovery methods
20.75               (for example by using `find_namespace_packages(...)`/`find_namespace:`
20.75               instead of `find_packages(...)`/`find:`).
20.75       
20.75               You can read more about "package discovery" on setuptools documentation page:
20.75       
20.75               - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html
20.75       
20.75               If you don't want 'uvloop.handles' to be distributed and are
20.75               already explicitly excluding 'uvloop.handles' via
20.75               `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
20.75               you can try to use `exclude_package_data`, or `include-package-data=False` in
20.75               combination with a more fine grained `package-data` configuration.
20.75       
20.75               You can read more about "package data files" on setuptools documentation page:
20.75       
20.75               - https://setuptools.pypa.io/en/latest/userguide/datafiles.html
20.75       
20.75       
20.75               [^1]: For Python, any directory (with suitable naming) can be imported,
20.75                     even if it does not contain any `.py` files.
20.75                     On the other hand, currently there is no concept of package data
20.75                     directory, all directories are treated like packages.
20.75               ********************************************************************************
20.75       
20.75       !!
20.75         check.warn(importable)
20.75       /tmp/pip-build-env-cugjg79y/overlay/lib/python3.13/site-packages/setuptools/command/build_py.py:218: _Warning: Package 'uvloop.includes' is absent from the `packages` configuration.
20.75       !!
20.75       
20.75               ********************************************************************************
20.75               ############################
20.75               # Package would be ignored #
20.75               ############################
20.75               Python recognizes 'uvloop.includes' as an importable package[^1],
20.75               but it is absent from setuptools' `packages` configuration.
20.75       
20.75               This leads to an ambiguous overall configuration. If you want to distribute this
20.75               package, please make sure that 'uvloop.includes' is explicitly added
20.75               to the `packages` configuration field.
20.75       
20.75               Alternatively, you can also rely on setuptools' discovery methods
20.75               (for example by using `find_namespace_packages(...)`/`find_namespace:`
20.75               instead of `find_packages(...)`/`find:`).
20.75       
20.75               You can read more about "package discovery" on setuptools documentation page:
20.75       
20.75               - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html
20.75       
20.75               If you don't want 'uvloop.includes' to be distributed and are
20.75               already explicitly excluding 'uvloop.includes' via
20.75               `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
20.75               you can try to use `exclude_package_data`, or `include-package-data=False` in
20.75               combination with a more fine grained `package-data` configuration.
20.75       
20.75               You can read more about "package data files" on setuptools documentation page:
20.75       
20.75               - https://setuptools.pypa.io/en/latest/userguide/datafiles.html
20.75       
20.75       
20.75               [^1]: For Python, any directory (with suitable naming) can be imported,
20.75                     even if it does not contain any `.py` files.
20.75                     On the other hand, currently there is no concept of package data
20.75                     directory, all directories are treated like packages.
20.75               ********************************************************************************
20.75       
20.75       !!
20.75         check.warn(importable)
20.75       copying uvloop/cbhandles.pxd -> build/lib.linux-x86_64-cpython-313/uvloop
20.75       copying uvloop/cbhandles.pyx -> build/lib.linux-x86_64-cpython-313/uvloop
20.75       copying uvloop/dns.pyx -> build/lib.linux-x86_64-cpython-313/uvloop
20.75       copying uvloop/errors.pyx -> build/lib.linux-x86_64-cpython-313/uvloop
20.75       copying uvloop/loop.pxd -> build/lib.linux-x86_64-cpython-313/uvloop
20.75       copying uvloop/loop.pyi -> build/lib.linux-x86_64-cpython-313/uvloop
20.75       copying uvloop/loop.pyx -> build/lib.linux-x86_64-cpython-313/uvloop
20.75       copying uvloop/lru.pyx -> build/lib.linux-x86_64-cpython-313/uvloop
20.75       copying uvloop/pseudosock.pyx -> build/lib.linux-x86_64-cpython-313/uvloop
20.75       copying uvloop/py.typed -> build/lib.linux-x86_64-cpython-313/uvloop
20.75       copying uvloop/request.pxd -> build/lib.linux-x86_64-cpython-313/uvloop
20.75       copying uvloop/request.pyx -> build/lib.linux-x86_64-cpython-313/uvloop
20.75       copying uvloop/server.pxd -> build/lib.linux-x86_64-cpython-313/uvloop
20.75       copying uvloop/server.pyx -> build/lib.linux-x86_64-cpython-313/uvloop
20.75       copying uvloop/sslproto.pxd -> build/lib.linux-x86_64-cpython-313/uvloop
20.75       copying uvloop/sslproto.pyx -> build/lib.linux-x86_64-cpython-313/uvloop
20.75       creating build/lib.linux-x86_64-cpython-313/uvloop/handles
20.75       copying uvloop/handles/async_.pxd -> build/lib.linux-x86_64-cpython-313/uvloop/handles
20.75       copying uvloop/handles/async_.pyx -> build/lib.linux-x86_64-cpython-313/uvloop/handles
20.75       copying uvloop/handles/basetransport.pxd -> build/lib.linux-x86_64-cpython-313/uvloop/handles
20.75       copying uvloop/handles/basetransport.pyx -> build/lib.linux-x86_64-cpython-313/uvloop/handles
20.75       copying uvloop/handles/check.pxd -> build/lib.linux-x86_64-cpython-313/uvloop/handles
20.75       copying uvloop/handles/check.pyx -> build/lib.linux-x86_64-cpython-313/uvloop/handles
20.75       copying uvloop/handles/fsevent.pxd -> build/lib.linux-x86_64-cpython-313/uvloop/handles
20.75       copying uvloop/handles/fsevent.pyx -> build/lib.linux-x86_64-cpython-313/uvloop/handles
20.75       copying uvloop/handles/handle.pxd -> build/lib.linux-x86_64-cpython-313/uvloop/handles
20.75       copying uvloop/handles/handle.pyx -> build/lib.linux-x86_64-cpython-313/uvloop/handles
20.75       copying uvloop/handles/idle.pxd -> build/lib.linux-x86_64-cpython-313/uvloop/handles
20.75       copying uvloop/handles/idle.pyx -> build/lib.linux-x86_64-cpython-313/uvloop/handles
20.75       copying uvloop/handles/pipe.pxd -> build/lib.linux-x86_64-cpython-313/uvloop/handles
20.75       copying uvloop/handles/pipe.pyx -> build/lib.linux-x86_64-cpython-313/uvloop/handles
20.75       copying uvloop/handles/poll.pxd -> build/lib.linux-x86_64-cpython-313/uvloop/handles
20.75       copying uvloop/handles/poll.pyx -> build/lib.linux-x86_64-cpython-313/uvloop/handles
20.75       copying uvloop/handles/process.pxd -> build/lib.linux-x86_64-cpython-313/uvloop/handles
20.75       copying uvloop/handles/process.pyx -> build/lib.linux-x86_64-cpython-313/uvloop/handles
20.75       copying uvloop/handles/stream.pxd -> build/lib.linux-x86_64-cpython-313/uvloop/handles
20.75       copying uvloop/handles/stream.pyx -> build/lib.linux-x86_64-cpython-313/uvloop/handles
20.75       copying uvloop/handles/streamserver.pxd -> build/lib.linux-x86_64-cpython-313/uvloop/handles
20.75       copying uvloop/handles/streamserver.pyx -> build/lib.linux-x86_64-cpython-313/uvloop/handles
20.75       copying uvloop/handles/tcp.pxd -> build/lib.linux-x86_64-cpython-313/uvloop/handles
20.75       copying uvloop/handles/tcp.pyx -> build/lib.linux-x86_64-cpython-313/uvloop/handles
20.75       copying uvloop/handles/timer.pxd -> build/lib.linux-x86_64-cpython-313/uvloop/handles
20.75       copying uvloop/handles/timer.pyx -> build/lib.linux-x86_64-cpython-313/uvloop/handles
20.75       copying uvloop/handles/udp.pxd -> build/lib.linux-x86_64-cpython-313/uvloop/handles
20.75       copying uvloop/handles/udp.pyx -> build/lib.linux-x86_64-cpython-313/uvloop/handles
20.75       creating build/lib.linux-x86_64-cpython-313/uvloop/includes
20.75       copying uvloop/includes/__init__.py -> build/lib.linux-x86_64-cpython-313/uvloop/includes
20.75       copying uvloop/includes/consts.pxi -> build/lib.linux-x86_64-cpython-313/uvloop/includes
20.75       copying uvloop/includes/debug.pxd -> build/lib.linux-x86_64-cpython-313/uvloop/includes
20.75       copying uvloop/includes/flowcontrol.pxd -> build/lib.linux-x86_64-cpython-313/uvloop/includes
20.75       copying uvloop/includes/python.pxd -> build/lib.linux-x86_64-cpython-313/uvloop/includes
20.75       copying uvloop/includes/stdlib.pxi -> build/lib.linux-x86_64-cpython-313/uvloop/includes
20.75       copying uvloop/includes/system.pxd -> build/lib.linux-x86_64-cpython-313/uvloop/includes
20.75       copying uvloop/includes/uv.pxd -> build/lib.linux-x86_64-cpython-313/uvloop/includes
20.75       running build_ext
20.75       checking for a BSD-compatible install... /usr/bin/install -c
20.75       checking whether build environment is sane... yes
20.75       checking for a race-free mkdir -p... /usr/bin/mkdir -p
20.75       checking for gawk... no
20.75       checking for mawk... mawk
20.75       checking whether make sets $(MAKE)... no
20.75       checking whether make supports nested variables... no
20.75       checking whether to enable maintainer-specific portions of Makefiles... yes
20.75       checking build system type... x86_64-pc-linux-gnu
20.75       checking host system type... x86_64-pc-linux-gnu
20.75       checking for gcc... no
20.75       checking for cc... no
20.75       checking for cl.exe... no
20.75       checking for clang... no
20.75       configure: error: in `/tmp/pip-install-fkwrynj9/uvloop_edd4da0dcc9d43729a47695ebc5496e5/build/libuv-x86_64':
20.75       configure: error: no acceptable C compiler found in $PATH
20.75       See `config.log' for more details
20.75       Traceback (most recent call last):
20.75         File "/usr/local/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
20.75           main()
20.75           ~~~~^^
20.75         File "/usr/local/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
20.75           json_out['return_val'] = hook(**hook_input['kwargs'])
20.75                                    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
20.75         File "/usr/local/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
20.75           return _build_backend().build_wheel(wheel_directory, config_settings,
20.75                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
20.75                                               metadata_directory)
20.75                                               ^^^^^^^^^^^^^^^^^^^
20.75         File "/tmp/pip-build-env-cugjg79y/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 421, in build_wheel
20.75           return self._build_with_temp_dir(
20.75                  ~~~~~~~~~~~~~~~~~~~~~~~~~^
20.75               ['bdist_wheel'],
20.75               ^^^^^^^^^^^^^^^^
20.75           ...<3 lines>...
20.75               self._arbitrary_args(config_settings),
20.75               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
20.75           )
20.75           ^
20.75         File "/tmp/pip-build-env-cugjg79y/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 403, in _build_with_temp_dir
20.75           self.run_setup()
20.75           ~~~~~~~~~~~~~~^^
20.75         File "/tmp/pip-build-env-cugjg79y/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 318, in run_setup
20.75           exec(code, locals())
20.75           ~~~~^^^^^^^^^^^^^^^^
20.75         File "<string>", line 237, in <module>
20.75         File "/tmp/pip-build-env-cugjg79y/overlay/lib/python3.13/site-packages/setuptools/__init__.py", line 117, in setup
20.75           return distutils.core.setup(**attrs)
20.75                  ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
20.75         File "/tmp/pip-build-env-cugjg79y/overlay/lib/python3.13/site-packages/setuptools/_distutils/core.py", line 183, in setup
20.75           return run_commands(dist)
20.75         File "/tmp/pip-build-env-cugjg79y/overlay/lib/python3.13/site-packages/setuptools/_distutils/core.py", line 199, in run_commands
20.75           dist.run_commands()
20.75           ~~~~~~~~~~~~~~~~~^^
20.75         File "/tmp/pip-build-env-cugjg79y/overlay/lib/python3.13/site-packages/setuptools/_distutils/dist.py", line 954, in run_commands
20.75           self.run_command(cmd)
20.75           ~~~~~~~~~~~~~~~~^^^^^
20.75         File "/tmp/pip-build-env-cugjg79y/overlay/lib/python3.13/site-packages/setuptools/dist.py", line 950, in run_command
20.75           super().run_command(command)
20.75           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^
20.75         File "/tmp/pip-build-env-cugjg79y/overlay/lib/python3.13/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
20.75           cmd_obj.run()
20.75           ~~~~~~~~~~~^^
20.75         File "/tmp/pip-build-env-cugjg79y/overlay/lib/python3.13/site-packages/setuptools/command/bdist_wheel.py", line 398, in run
20.75           self.run_command("build")
20.75           ~~~~~~~~~~~~~~~~^^^^^^^^^
20.75         File "/tmp/pip-build-env-cugjg79y/overlay/lib/python3.13/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
20.75           self.distribution.run_command(command)
20.75           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
20.75         File "/tmp/pip-build-env-cugjg79y/overlay/lib/python3.13/site-packages/setuptools/dist.py", line 950, in run_command
20.75           super().run_command(command)
20.75           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^
20.75         File "/tmp/pip-build-env-cugjg79y/overlay/lib/python3.13/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
20.75           cmd_obj.run()
20.75           ~~~~~~~~~~~^^
20.75         File "/tmp/pip-build-env-cugjg79y/overlay/lib/python3.13/site-packages/setuptools/_distutils/command/build.py", line 135, in run
20.75           self.run_command(cmd_name)
20.75           ~~~~~~~~~~~~~~~~^^^^^^^^^^
20.75         File "/tmp/pip-build-env-cugjg79y/overlay/lib/python3.13/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
20.75           self.distribution.run_command(command)
20.75           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
20.75         File "/tmp/pip-build-env-cugjg79y/overlay/lib/python3.13/site-packages/setuptools/dist.py", line 950, in run_command
20.75           super().run_command(command)
20.75           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^
20.75         File "/tmp/pip-build-env-cugjg79y/overlay/lib/python3.13/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
20.75           cmd_obj.run()
20.75           ~~~~~~~~~~~^^
20.75         File "/tmp/pip-build-env-cugjg79y/overlay/lib/python3.13/site-packages/setuptools/command/build_ext.py", line 98, in run
20.75           _build_ext.run(self)
20.75           ~~~~~~~~~~~~~~^^^^^^
20.75         File "/tmp/pip-build-env-cugjg79y/overlay/lib/python3.13/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
20.75           _build_ext.build_ext.run(self)
20.75           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
20.75         File "/tmp/pip-build-env-cugjg79y/overlay/lib/python3.13/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
20.75           self.build_extensions()
20.75           ~~~~~~~~~~~~~~~~~~~~~^^
20.75         File "<string>", line 200, in build_extensions
20.75         File "<string>", line 175, in build_libuv
20.75         File "/usr/local/lib/python3.13/subprocess.py", line 577, in run
20.75           raise CalledProcessError(retcode, process.args,
20.75                                    output=stdout, stderr=stderr)
20.75       subprocess.CalledProcessError: Command '['./configure']' returned non-zero exit status 1.
20.75       [end of output]
20.75   
20.75   note: This error originates from a subprocess, and is likely not a problem with pip.
20.75   ERROR: Failed building wheel for uvloop
20.75 Failed to build httptools uvloop
```

**Comment by z0z0r4** [comment]
已经不需要 uvciron
